### ISSUE TITLE
Compile (make) failing under ArchLinux

### ISSUE THREAD

**Issue by gwally9** [sergev/baoclone#11]
Tried running make under ArchLinux (latest container) and get: 

`DAC(9)[Sun Feb 21 10:03:56:/target]# make
make: git: No such file or directory
gcc -m64 -g -O -Wall -Werror -DVERSION='"1.5."'   -c -o main.o main.c
make: git: No such file or directory
gcc -m64 -g -O -Wall -Werror -DVERSION='"1.5."'   -c -o util.o util.c
make: git: No such file or directory
gcc -m64 -g -O -Wall -Werror -DVERSION='"1.5."'   -c -o radio.o radio.c
make: git: No such file or directory
gcc -m64 -g -O -Wall -Werror -DVERSION='"1.5."'   -c -o uv-5r.o uv-5r.c
make: git: No such file or directory
gcc -m64 -g -O -Wall -Werror -DVERSION='"1.5."'   -c -o uv-b5.o uv-b5.c
make: git: No such file or directory
gcc -m64 -g -O -Wall -Werror -DVERSION='"1.5."'   -c -o bf-888s.o bf-888s.c
make: git: No such file or directory
gcc -m64 -g -O -Wall -Werror -DVERSION='"1.5."'   -c -o bf-t1.o bf-t1.c
gcc -m64  -o baoclone main.o util.o radio.o uv-5r.o uv-b5.o bf-888s.o bf-t1.o
/usr/sbin/ld: util.o:/target/util.h:53: multiple definition of `verbose'; main.o:/target/util.h:53: first defined here
/usr/sbin/ld: radio.o:/target/util.h:53: multiple definition of `verbose'; main.o:/target/util.h:53: first defined here
/usr/sbin/ld: radio.o:/target/radio.h:110: multiple definition of `radio_port'; main.o:/target/radio.h:110: first defined here
/usr/sbin/ld: radio.o:/target/radio.h:115: multiple definition of `radio_progress'; main.o:/target/radio.h:115: first defined here
/usr/sbin/ld: uv-5r.o:/target/util.h:53: multiple definition of `verbose'; main.o:/target/util.h:53: first defined here
/usr/sbin/ld: uv-5r.o:/target/radio.h:115: multiple definition of `radio_progress'; main.o:/target/radio.h:115: first defined here
/usr/sbin/ld: uv-5r.o:/target/radio.h:110: multiple definition of `radio_port'; main.o:/target/radio.h:110: first defined here
/usr/sbin/ld: uv-b5.o:/target/radio.h:110: multiple definition of `radio_port'; main.o:/target/radio.h:110: first defined here
/usr/sbin/ld: uv-b5.o:/target/util.h:53: multiple definition of `verbose'; main.o:/target/util.h:53: first defined here
/usr/sbin/ld: uv-b5.o:/target/radio.h:115: multiple definition of `radio_progress'; main.o:/target/radio.h:115: first defined here
/usr/sbin/ld: bf-888s.o:/target/util.h:53: multiple definition of `verbose'; main.o:/target/util.h:53: first defined here
/usr/sbin/ld: bf-888s.o:/target/radio.h:115: multiple definition of `radio_progress'; main.o:/target/radio.h:115: first defined here
/usr/sbin/ld: bf-888s.o:/target/radio.h:110: multiple definition of `radio_port'; main.o:/target/radio.h:110: first defined here
/usr/sbin/ld: bf-t1.o:/target/radio.h:110: multiple definition of `radio_port'; main.o:/target/radio.h:110: first defined here
/usr/sbin/ld: bf-t1.o:/target/util.h:53: multiple definition of `verbose'; main.o:/target/util.h:53: first defined here
/usr/sbin/ld: bf-t1.o:/target/radio.h:115: multiple definition of `radio_progress'; main.o:/target/radio.h:115: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:19: baoclone] Error 1`

**Comment by Lexiyntax** [comment]
Looks like this to me:

https://github.com/Lexiyntax/baoclone/commit/2560e2f5b7b6d8b7f741a57d9029be288dae7a9d

If this works for you I can submit a PR for it.

**Comment by sergev** [comment]
Closing this issue as fixed.
